# output dir will be created by hydra
data_dir: /diffusionvol/data/jetnet/
output_dir: /diffusionvol/experiments/

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
